# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("compliance", "0002_enhance_compliance_add_accidents"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accident_reports",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="compliancecategory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_categories",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="peaceofmindscore",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peace_of_mind_scores",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="ramsdocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rams_documents",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assessments",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
