# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("accounts", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.tenantsettings",
            ),
        ),
    ]
