# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("bookings", "0014_add_reminder_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_staff",
                to="tenants.tenantsettings",
            ),
        ),
    ]
