# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="tenants.tenantsettings",
            ),
        ),
    ]
