# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("documents", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_tags",
                to="tenants.tenantsettings",
            ),
        ),
        migrations.AlterField(
            model_name="documenttag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
