# Generated by Django 4.2.9 on 2026-02-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("staff", "0002_workinghours_timesheetentry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timesheetentry",
            new_name="staff_times_staff_i_23ef5f_idx",
            old_name="staff_timesh_staff_i_idx",
        ),
        migrations.RenameIndex(
            model_name="workinghours",
            new_name="staff_worki_staff_i_adf3b3_idx",
            old_name="staff_workin_staff_i_idx",
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profiles",
                to="tenants.tenantsettings",
            ),
        ),
    ]
